# render.yaml
services:
  - type: web
    name: techpath-django-backend
    env: python
    region: oregon
    plan: free
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - requirements.txt
        - render.yaml
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

      echo "Building frontend..."
      cd frontend
      yarn install --frozen-lockfile
      yarn build
      echo "Frontend build complete."
      cd .. # Back to project root

      echo "Copying frontend build from frontend/dist to backend/build..."
      mkdir -p backend/build # Ensure target directory exists
      cp -r frontend/dist/* backend/build/
      echo "Frontend assets copied."

      echo "Preparing Django..."
      cd backend
      python manage.py migrate --noinput
      echo "Django preparation complete."
      cd ..

    startCommand: "cd backend && gunicorn techpath.wsgi --bind 0.0.0.0:\$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: DJANGO_SETTINGS_MODULE
        value: "techpath.settings"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    healthCheckPath: /api/suggest-path/
